### ISSUE TITLE
When we try to automate the release of extension via jenkins, it is ask for input

### ISSUE THREAD

**Issue by Divyaabcd** [adobe/reactor-releaser#13]
### Expected Behaviour
not able to execute the release by just providing command line arguments
### Actual Behaviour
asks for input to confirm whether to release the extension or not
### Reproduce Scenario (including but not limited to)
When I try to excecute below command
npx @adobe/reactor-releaser --private-key=/Users/jane/launchkeys/reactor_integration_private.key --org-id=01C20D883A7D42080A494212@AdobeOrg --tech-account-id=14A533A72B181CF90A44410D@techacct.adobe.com --api-key=192ce541b1144160941a83vb74e0e74d --client-secret=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

it asks for input
An extension package with the name \
exp ext at version 
20.23.1 with development 
availability was found on the server. Would you like to release 
this extension package to private availability?

#### Steps to Reproduce
Try to release extension via jenkins using below command
An extension package with the name \
${extensionPackageFromServer.attributes.name} at version \
${extensionPackageFromServer.attributes.version} with development \
availability was found on the server. Would you like to release \
this extension package to private availability?

**Comment by thebenrob** [comment]
Releasing an extension requires that you make a PATCH call to the extension package resource itself and update the `availability` attribute.  I think what is happening when you run this command is that we're looking in the extension.json file for the extension `name`, then looking up that `name` on the server to find the correct ID, then prompting you to confirm that we got the right ID before we release it.  If you know the ID of the extension package, you can skip the releaser entirely and just make the appropriate CURL command (https://developer.adobelaunch.com/api/reference/1.0/extension_packages/release_private/ has details).

I can also discuss with the team the option of having being able to specify the extension package ID directly with a command line argument, but that'll definitely take longer.

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL as Story

**Comment by brenthosie** [comment]
Thanks for bringing this to our attention

**Comment by mems** [comment]
In case someone use an old version (before [v3.1.0](https://github.com/adobe/reactor-releaser/releases/tag/v3.1.0)), he could use it stdin to confirm automatically:
```
printf 'y\n' | npx @adobe/reactor-releaser ....
```

Note this "new" argument (`--confirm-package-release`) is undocumented
