### ISSUE TITLE
OAuth Server-to-Server credential support

### ISSUE THREAD

**Issue by mems** [adobe/reactor-releaser#28]
Currently Service Account (JWT) using private key is the only credential type supported by reactor-releaser.

But [the Service Account (JWT) credentials have been deprecated in favor of the new OAuth Server-to-Server credentials](https://developer.adobe.com/developer-console/docs/guides/authentication/ServerToServerAuthentication/migration/).

See also https://github.com/adobe/reactor-uploader/issues/63

**Comment by brenthosie** [comment]
this is now in beta and will go public later: https://github.com/adobe/reactor-releaser/releases/tag/v4.0.0-beta.3
